# Uncomment the next line to define a global platform for your project
# platform :ios, 14.0'

target 'testeSicredi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testeSicredi
	pod 'RxSwift'
	pod 'RxCocoa'
  target 'testeSicrediTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testeSicrediUITests' do
    # Pods for testing
  end

end
